# Generated by Django 2.1 on 2018-10-22 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0002_auto_20180916_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='imgsrc',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
