# Generated by Django 2.1 on 2018-10-26 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0006_auto_20181026_1140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audio',
            name='text',
        ),
        migrations.AddField(
            model_name='audio',
            name='fulltitle',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='audio',
            name='title_speaker_join',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
