# Generated by Django 2.1 on 2018-10-26 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0008_audio_title_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio_detail',
            name='detail_pubdate',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
