# Generated by Django 2.1 on 2018-10-26 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0009_auto_20181026_1458'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audio_detail',
            name='detail_translator',
        ),
    ]
