# Generated by Django 2.1 on 2018-10-26 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0010_remove_audio_detail_detail_translator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio_detail',
            name='detail_imgsrc',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='audio_detail',
            name='detail_outline',
            field=models.TextField(null=True),
        ),
    ]
