# Generated by Django 2.1 on 2018-10-26 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0011_auto_20181026_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio_detail',
            name='detail_playtime',
            field=models.CharField(max_length=10),
        ),
    ]
