# Generated by Django 2.1 on 2018-10-26 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0012_auto_20181026_1504'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audio',
            name='audiosrc',
        ),
        migrations.AddField(
            model_name='audio_detail',
            name='detail_audiosrc',
            field=models.CharField(default='def', max_length=255),
            preserve_default=False,
        ),
    ]
