# Generated by Django 2.1 on 2018-10-29 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0013_auto_20181026_1534'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audio_detail',
            name='detail_text',
        ),
        migrations.AddField(
            model_name='audio_detail',
            name='detail_author_text',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='audio_detail',
            name='detail_speaker_text',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='audio_detail',
            name='detail_title_text',
            field=models.TextField(null=True),
        ),
    ]
