# Generated by Django 2.1 on 2018-11-01 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0014_auto_20181029_1048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audio',
            name='published_date',
        ),
    ]
