# Generated by Django 2.1 on 2018-11-01 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0016_auto_20181101_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='title_author',
            field=models.CharField(default='tt', max_length=5, null=True),
        ),
    ]
