# Generated by Django 2.1 on 2018-11-14 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0017_auto_20181101_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio_detail',
            name='detail_title',
            field=models.CharField(max_length=50),
        ),
    ]
